version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build:
      context: ./frontend
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
